Add built-in conditions
SunDwarf/curious pull request #25
Opened 2018-06-07 20:19 UTC by TildeBeta

2018-06-07 20:21 UTC, TildeBeta commented
I'll add docstrings soon

2018-06-07 20:23 UTC, Fuyukai requested changes

2018-06-07 20:23 UTC, Fuyukai commented on curious/commands/decorators.py
> +            func.cmd_owner_bypass = True
`func.cmd_owner_bypass = bypass_owner`

2018-06-07 20:23 UTC, Fuyukai commented on curious/commands/conditions.py
> +        author_roles = [role.name for role in ctx.author.roles]
Make this a set comprehension so that the `in` check below is constant time (and probably faster).

2018-06-07 20:23 UTC, Fuyukai commented on curious/commands/conditions.py
> +        bot_roles = [role.name for role in ctx.guild.me.roles]
Same here.

2018-06-07 20:23 UTC, Fuyukai commented on curious/commands/conditions.py
> +        return ctx.author == ctx.guild.owner
Compare IDs instead of objects.

2018-06-10 15:28 UTC, Fuyukai requested changes

2018-06-10 15:28 UTC, Fuyukai commented on curious/commands/conditions.py
> +    The role names must be exact matches.
`must all be` rather than `must be`.

2018-06-10 15:28 UTC, Fuyukai commented on curious/commands/decorators.py
> +        if bypass_owner is True:
Useless if statement

2018-06-10 15:28 UTC, Fuyukai commented on curious/commands/conditions.py
> +        return all(getattr(perms, name, None) == value
Since perms are gonna be True/False/None, do an identity check instead.

2018-06-10 15:28 UTC, Fuyukai commented on curious/commands/conditions.py
> +        return ctx.author.id == ctx.guild.owner.id
This is a functionally useless ID comparison. Use `ctx.message.author_id == ctx.guild.owner_id`.

2018-06-10 15:28 UTC, Fuyukai commented on curious/commands/context.py
> +                if self.author.id == application.owner.id:
Use `self.message.author_id` instead. Faster, and won't explode out of nowhere if Discord sends terrible packets.

2018-06-10 15:28 UTC, Fuyukai commented
You also need to add `conditions` to the autosummary in `commands/__init__.py`.

2018-06-10 15:47 UTC, Fuyukai approved these changes

2018-06-10 15:48 UTC, merged