add feature to reorder channel positions
SunDwarf/curious pull request #35
Opened 2018-06-22 14:31 UTC by brakhane

2018-06-22 16:12 UTC, Fuyukai commented
Huh. I never realised I didn't actually implement this. Thanks.

2018-06-22 16:13 UTC, Fuyukai requested changes

2018-06-22 16:13 UTC, Fuyukai commented on curious/core/httpclient.py
> +        data = await self.patch(url, bucket="channels:{}".format(channel_ids_and_positions[0][0]), json=payload)
The bucket should be for the guild ID, not the channel.

2018-06-22 17:31 UTC, brakhane commented
Fixed.

There is currently a corner case that's not handled: When one of the channels gets changed by something else, and we get the channel_update event from that, we assume that it's the position one.

The more correct approach would be to actually check for the expected position, but since I'm not sure that wouldn't run into corner cases as well, and it's highly unlikely anyway, I ignore that.

2018-06-23 14:59 UTC, Fuyukai approved these changes

2018-06-23 14:59 UTC, merged